// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConn() {
  return window['go']['main']['App']['CheckConn']();
}

export function GetGamesData() {
  return window['go']['main']['App']['GetGamesData']();
}

export function GetGamesList() {
  return window['go']['main']['App']['GetGamesList']();
}

export function GetPins() {
  return window['go']['main']['App']['GetPins']();
}

export function PinGame(arg1) {
  return window['go']['main']['App']['PinGame'](arg1);
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function SetGame(arg1, arg2) {
  return window['go']['main']['App']['SetGame'](arg1, arg2);
}
