// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConn():Promise<boolean>;

export function GetGamesData():Promise<void>;

export function GetGamesList():Promise<string>;

export function GetPins():Promise<string>;

export function PinGame(arg1:string):Promise<void>;

export function Reconnect():Promise<boolean>;

export function SetGame(arg1:string,arg2:string):Promise<void>;
